Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when 
increasing is False, the i-th output column is the input vector raised element-wise to the power 
of N - i - 1.

In [1]:
import numpy as np

In [5]:
def vender(ipvec, col, increasing=False):
    
    if not increasing:
        op_mat = np.array([x**(col-1-i) for x in ipvec for i in range(col)]).reshape(ipvec.size,col)
    elif increasing:
        op_mat = np.array([x**i for x in ipvec for i in range(col)]).reshape(ipvec.size,col)
    
    return op_mat

In [8]:
inputvac = np.array([1,2,3,4,5])
col = 4
decrease = vender(inputvac,col,False)
increase = vender(inputvac,col,True)

In [9]:
print("The input array is:",inputvac,"\n")
print("Number of columns in output matrix should be:",col,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",decrease,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",increase,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 



Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [11]:
inp=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [89]:
def movavg(k,n,i,it):
    avg=[]
    count=0
    lpc=0
    temp=0
    while(it<=i):
        count=0
        temp=0
        for j in range(lpc,n):
            if(count==k):
                break
            else:
                temp = temp+inp[j]
                count=count+1
        avg.append(temp/k)
        lpc=lpc+1
        it=it+1
    return avg

In [90]:
k=3
n=13
i=n-k+1
it=1

In [91]:
mavg=movavg(k,n,i,it)
print(mavg)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
